# -*- coding: utf-8 -*-
from PyQt5 import QtCore, QtGui, QtWidgets
from myBattery import QmyBattery

class Ui_CoreUI(object):
    def setupUi(self, CoreUI):
        CoreUI.setObjectName("CoreUI")
        CoreUI.resize(1165, 727)
        self.centralwidget = QtWidgets.QWidget(CoreUI)
        self.centralwidget.setObjectName("centralwidget")
        self.systemSettingsGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.systemSettingsGroupBox.setGeometry(QtCore.QRect(800, 640, 20, 71))
        self.systemSettingsGroupBox.setTitle("")
        self.systemSettingsGroupBox.setObjectName("systemSettingsGroupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.systemSettingsGroupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_2 = QtWidgets.QLabel(self.systemSettingsGroupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)
        self.webcamGroupBox = QtWidgets.QGroupBox(self.systemSettingsGroupBox)
        self.webcamGroupBox.setTitle("")
        self.webcamGroupBox.setObjectName("webcamGroupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.webcamGroupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label = QtWidgets.QLabel(self.webcamGroupBox)
        self.label.setStyleSheet("color:rgb(255, 255, 255)")
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.webcamGroupBox, 1, 0, 1, 1)
        self.dbGroupBox = QtWidgets.QGroupBox(self.systemSettingsGroupBox)
        self.dbGroupBox.setTitle("")
        self.dbGroupBox.setObjectName("dbGroupBox")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.dbGroupBox)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_6 = QtWidgets.QLabel(self.dbGroupBox)
        self.label_6.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_6.setObjectName("label_6")
        self.gridLayout_6.addWidget(self.label_6, 0, 0, 1, 1)
        self.initDbButton = QtWidgets.QPushButton(self.dbGroupBox)
        self.initDbButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.initDbButton.setAutoDefault(False)
        self.initDbButton.setObjectName("initDbButton")
        self.gridLayout_6.addWidget(self.initDbButton, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.dbGroupBox, 2, 0, 1, 1)
        self.dbGroupBox.raise_()
        self.webcamGroupBox.raise_()
        self.label_2.raise_()
        self.realTimeCaptureGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.realTimeCaptureGroupBox.setGeometry(QtCore.QRect(40, 90, 791, 501))
        self.realTimeCaptureGroupBox.setTitle("")
        self.realTimeCaptureGroupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.realTimeCaptureGroupBox.setFlat(False)
        self.realTimeCaptureGroupBox.setObjectName("realTimeCaptureGroupBox")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.realTimeCaptureGroupBox)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.realTimeCaptureLabel = QtWidgets.QLabel(self.realTimeCaptureGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.realTimeCaptureLabel.sizePolicy().hasHeightForWidth())
        self.realTimeCaptureLabel.setSizePolicy(sizePolicy)
        self.realTimeCaptureLabel.setStyleSheet("border:none")
        self.realTimeCaptureLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.realTimeCaptureLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.realTimeCaptureLabel.setObjectName("realTimeCaptureLabel")
        self.gridLayout_8.addWidget(self.realTimeCaptureLabel, 0, 0, 2, 2)
        self.widget = QtWidgets.QWidget(self.realTimeCaptureGroupBox)
        self.widget.setObjectName("widget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.startWebcamButton = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startWebcamButton.sizePolicy().hasHeightForWidth())
        self.startWebcamButton.setSizePolicy(sizePolicy)
        self.startWebcamButton.setMinimumSize(QtCore.QSize(60, 60))
        self.startWebcamButton.setMaximumSize(QtCore.QSize(60, 60))
        self.startWebcamButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.startWebcamButton.setText("")
        self.startWebcamButton.setIconSize(QtCore.QSize(30, 30))
        self.startWebcamButton.setAutoDefault(False)
        self.startWebcamButton.setDefault(False)
        self.startWebcamButton.setFlat(True)
        self.startWebcamButton.setObjectName("startWebcamButton")
        self.gridLayout_7.addWidget(self.startWebcamButton, 0, 0, 1, 1, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)
        self.gridLayout_8.addWidget(self.widget, 1, 1, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.realTimeCaptureGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.debugCheckBox = QtWidgets.QCheckBox(self.widget_2)
        self.debugCheckBox.setChecked(True)
        self.debugCheckBox.setObjectName("debugCheckBox")
        self.horizontalLayout_3.addWidget(self.debugCheckBox)
        self.pushButton_10 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_10.setText("")
        self.pushButton_10.setFlat(True)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_3.addWidget(self.pushButton_10)
        self.equalizeHistCheckBox = QtWidgets.QCheckBox(self.widget_2)
        self.equalizeHistCheckBox.setObjectName("equalizeHistCheckBox")
        self.horizontalLayout_3.addWidget(self.equalizeHistCheckBox)
        self.pushButton_9 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_9.setText("")
        self.pushButton_9.setFlat(True)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_3.addWidget(self.pushButton_9)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.gridLayout_8.addWidget(self.widget_2, 2, 0, 1, 2)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(1120, 0, 40, 40))
        self.pushButton_4.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setStyleSheet("")
        self.pushButton_4.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../关闭.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon)
        self.pushButton_4.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_4.setAutoRepeatDelay(300)
        self.pushButton_4.setFlat(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.logGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.logGroupBox.setGeometry(QtCore.QRect(880, 260, 276, 431))
        self.logGroupBox.setStyleSheet("")
        self.logGroupBox.setTitle("")
        self.logGroupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.logGroupBox.setObjectName("logGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.logGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(self.logGroupBox)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.logTextEdit = QtWidgets.QTextEdit(self.logGroupBox)
        self.logTextEdit.setStyleSheet("")
        self.logTextEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.logTextEdit.setObjectName("logTextEdit")
        self.gridLayout.addWidget(self.logTextEdit, 1, 0, 1, 1)
        self.pushButton_full = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_full.setGeometry(QtCore.QRect(1080, 0, 40, 40))
        self.pushButton_full.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_full.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_full.setStyleSheet("")
        self.pushButton_full.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../全屏.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_full.setIcon(icon1)
        self.pushButton_full.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_full.setAutoRepeatDelay(300)
        self.pushButton_full.setFlat(True)
        self.pushButton_full.setObjectName("pushButton_full")
        self.pushButton_min = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_min.setGeometry(QtCore.QRect(1040, 0, 40, 40))
        self.pushButton_min.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_min.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_min.setStyleSheet("")
        self.pushButton_min.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../最小化.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_min.setIcon(icon2)
        self.pushButton_min.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_min.setAutoRepeatDelay(300)
        self.pushButton_min.setFlat(True)
        self.pushButton_min.setObjectName("pushButton_min")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(1000, 0, 40, 40))
        self.pushButton_3.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("")
        self.pushButton_3.setText("")
        self.pushButton_3.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_3.setCheckable(True)
        self.pushButton_3.setAutoRepeatDelay(300)
        self.pushButton_3.setFlat(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 0, 301, 71))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.functionGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.functionGroupBox.setGeometry(QtCore.QRect(880, 90, 261, 111))
        self.functionGroupBox.setTitle("")
        self.functionGroupBox.setObjectName("functionGroupBox")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.functionGroupBox)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.pushButton_5 = QtWidgets.QPushButton(self.functionGroupBox)
        self.pushButton_5.setFlat(True)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_9.addWidget(self.pushButton_5, 0, 0, 1, 1)
        self.faceTrackerCheckBox = QtWidgets.QCheckBox(self.functionGroupBox)
        self.faceTrackerCheckBox.setText("")
        self.faceTrackerCheckBox.setChecked(True)
        self.faceTrackerCheckBox.setAutoRepeatInterval(106)
        self.faceTrackerCheckBox.setObjectName("faceTrackerCheckBox")
        self.gridLayout_9.addWidget(self.faceTrackerCheckBox, 0, 1, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.functionGroupBox)
        self.pushButton_6.setFlat(True)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_9.addWidget(self.pushButton_6, 1, 0, 1, 1)
        self.faceRecognizerCheckBox = QtWidgets.QCheckBox(self.functionGroupBox)
        self.faceRecognizerCheckBox.setEnabled(False)
        self.faceRecognizerCheckBox.setText("")
        self.faceRecognizerCheckBox.setObjectName("faceRecognizerCheckBox")
        self.gridLayout_9.addWidget(self.faceRecognizerCheckBox, 1, 1, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.functionGroupBox)
        self.pushButton_7.setFlat(True)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_9.addWidget(self.pushButton_7, 2, 0, 1, 1)
        self.panalarmCheckBox = QtWidgets.QCheckBox(self.functionGroupBox)
        self.panalarmCheckBox.setText("")
        self.panalarmCheckBox.setChecked(True)
        self.panalarmCheckBox.setObjectName("panalarmCheckBox")
        self.gridLayout_9.addWidget(self.panalarmCheckBox, 2, 1, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(1000, 220, 80, 21))
        self.pushButton_11.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_11.setFlat(True)
        self.pushButton_11.setObjectName("pushButton_11")
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(340, 20, 531, 60))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setSpacing(8)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton2 = QtWidgets.QPushButton(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton2.sizePolicy().hasHeightForWidth())
        self.pushButton2.setSizePolicy(sizePolicy)
        self.pushButton2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton2.setCheckable(True)
        self.pushButton2.setChecked(True)
        self.pushButton2.setFlat(True)
        self.pushButton2.setObjectName("pushButton2")
        self.buttonGroup = QtWidgets.QButtonGroup(CoreUI)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.pushButton2)
        self.horizontalLayout.addWidget(self.pushButton2)
        self.pushButton = QtWidgets.QPushButton(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setCheckable(True)
        self.pushButton.setChecked(False)
        self.pushButton.setObjectName("pushButton")
        self.buttonGroup.addButton(self.pushButton)
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setCheckable(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.buttonGroup.addButton(self.pushButton_2)
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(880, 220, 120, 23))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.useExternalCameraCheckBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.useExternalCameraCheckBox.setStyleSheet("")
        self.useExternalCameraCheckBox.setObjectName("useExternalCameraCheckBox")
        self.horizontalLayout_2.addWidget(self.useExternalCameraCheckBox)

        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.mp3Button = QtWidgets.QCheckBox(self.layoutWidget)
        self.mp3Button.setStyleSheet("")
        self.mp3Button.setObjectName("mp3Button")
        self.horizontalLayout_5.addWidget(self.mp3Button)

        self.pushButton_8 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_8.setText("")
        self.pushButton_8.setFlat(True)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_2.addWidget(self.pushButton_8)
        self.autoAlarmThresholdSlider = QtWidgets.QSlider(self.centralwidget)
        self.autoAlarmThresholdSlider.setGeometry(QtCore.QRect(490, 680, 279, 18))
        self.autoAlarmThresholdSlider.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.autoAlarmThresholdSlider.setMinimum(50)
        self.autoAlarmThresholdSlider.setMaximum(80)
        self.autoAlarmThresholdSlider.setSingleStep(1)
        self.autoAlarmThresholdSlider.setPageStep(5)
        self.autoAlarmThresholdSlider.setProperty("value", 65)
        self.autoAlarmThresholdSlider.set
        self.autoAlarmThresholdSlider.setOrientation(QtCore.Qt.Horizontal)
        self.autoAlarmThresholdSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.autoAlarmThresholdSlider.setObjectName("autoAlarmThresholdSlider")
        self.autoAlarmThresholdLabel = QtWidgets.QLabel(self.centralwidget)
        self.autoAlarmThresholdLabel.setGeometry(QtCore.QRect(530, 640, 77, 18))
        self.autoAlarmThresholdLabel.setStyleSheet("color:rgb(255, 255, 255)")
        self.autoAlarmThresholdLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.autoAlarmThresholdLabel.setObjectName("autoAlarmThresholdLabel")
        self.confidenceThresholdSlider = QtWidgets.QSlider(self.centralwidget)
        self.confidenceThresholdSlider.setGeometry(QtCore.QRect(140, 680, 197, 18))
        self.confidenceThresholdSlider.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.confidenceThresholdSlider.setMaximum(80)
        self.confidenceThresholdSlider.setSingleStep(1)
        self.confidenceThresholdSlider.setPageStep(5)
        self.confidenceThresholdSlider.setProperty("value", 50)
        self.confidenceThresholdSlider.setOrientation(QtCore.Qt.Horizontal)
        self.confidenceThresholdSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.confidenceThresholdSlider.setObjectName("confidenceThresholdSlider")
        self.confidenceThresholdLabel = QtWidgets.QLabel(self.centralwidget)
        self.confidenceThresholdLabel.setGeometry(QtCore.QRect(150, 640, 77, 18))
        self.confidenceThresholdLabel.setStyleSheet("color:red")
        self.confidenceThresholdLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.confidenceThresholdLabel.setObjectName("confidenceThresholdLabel")
        self.widget_3 = QmyBattery(self.centralwidget)
        self.widget_3.setGeometry(QtCore.QRect(40, 620, 80, 80))
        self.widget_3.setObjectName("widget_3")
        self.widget_4 = QtWidgets.QWidget(self.centralwidget)
        self.widget_4.setGeometry(QtCore.QRect(350, 620, 80, 80))
        self.widget_4.setObjectName("widget_4")
        CoreUI.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(CoreUI)
        self.statusbar.setObjectName("statusbar")
        CoreUI.setStatusBar(self.statusbar)

        self.retranslateUi(CoreUI)
        QtCore.QMetaObject.connectSlotsByName(CoreUI)

    def retranslateUi(self, CoreUI):
        _translate = QtCore.QCoreApplication.translate
        CoreUI.setWindowTitle(_translate("CoreUI", "OpenCV Face Recognition System - Core"))
        self.label_2.setText(_translate("CoreUI", "系统设置"))
        self.label.setText(_translate("CoreUI", "图像捕获"))
        self.label_6.setText(_translate("CoreUI", "人脸数据库"))
        self.initDbButton.setText(_translate("CoreUI", "数据库状态"))
        self.realTimeCaptureLabel.setText(_translate("CoreUI", "<html><head/><body><p><br/></p></body></html>"))
        self.debugCheckBox.setText(_translate("CoreUI", "调试模式"))
        self.equalizeHistCheckBox.setText(_translate("CoreUI", "直方图均衡化"))
        self.label_7.setText(_translate("CoreUI", "系统日志"))
        self.label_8.setText(_translate("CoreUI", "学生注意力检测系统"))
        self.pushButton_5.setText(_translate("CoreUI", "疲劳检测"))
        self.pushButton_6.setText(_translate("CoreUI", "人脸识别"))
        self.faceRecognizerCheckBox.setToolTip(_translate("CoreUI", "数据库未完成初始化，请检查"))
        self.pushButton_7.setText(_translate("CoreUI", "报警系统"))
        self.pushButton_11.setText(_translate("CoreUI", "检测画面截图"))
        self.pushButton2.setText(_translate("CoreUI", "疲劳检测"))
        self.pushButton.setText(_translate("CoreUI", "人脸采集"))
        self.pushButton_2.setText(_translate("CoreUI", "人脸数据库"))
        self.useExternalCameraCheckBox.setText(_translate("CoreUI", "外接摄像头"))
        self.mp3Button.setText(_translate("CoreUI", "开启语音播报"))
        self.autoAlarmThresholdLabel.setText(_translate("CoreUI", "自动报警阈值："))
        self.confidenceThresholdLabel.setText(_translate("CoreUI", "置信度阈值："))

